// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQ5f7HmRxlwvZC1d36dM4o6M2Z1Vr1kw',
    appId: '1:788173294268:web:1e4b7bc2142f1acf031eb9',
    messagingSenderId: '788173294268',
    projectId: 'budget-tracker-5c40f',
    authDomain: 'budget-tracker-5c40f.firebaseapp.com',
    storageBucket: 'budget-tracker-5c40f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsM5T21DOdHCCUfLreuKIZRwepEMtFI5E',
    appId: '1:788173294268:android:6b2a9363a4eda276031eb9',
    messagingSenderId: '788173294268',
    projectId: 'budget-tracker-5c40f',
    storageBucket: 'budget-tracker-5c40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQSATMaAIoMBmqVgPFO1kAyPDrD3JgvLo',
    appId: '1:788173294268:ios:879bd2a4d70a3b8e031eb9',
    messagingSenderId: '788173294268',
    projectId: 'budget-tracker-5c40f',
    storageBucket: 'budget-tracker-5c40f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQSATMaAIoMBmqVgPFO1kAyPDrD3JgvLo',
    appId: '1:788173294268:ios:7450452b7bd749a9031eb9',
    messagingSenderId: '788173294268',
    projectId: 'budget-tracker-5c40f',
    storageBucket: 'budget-tracker-5c40f.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbQ5f7HmRxlwvZC1d36dM4o6M2Z1Vr1kw',
    appId: '1:788173294268:web:23a2c2b80679cc7a031eb9',
    messagingSenderId: '788173294268',
    projectId: 'budget-tracker-5c40f',
    authDomain: 'budget-tracker-5c40f.firebaseapp.com',
    storageBucket: 'budget-tracker-5c40f.firebasestorage.app',
  );
}
